const examples = [
  {
    id: 1,
    title: "Example-1",
    _map: [
      "____X_X_XXX_X_XXXXX______",
      "_XX_XXX_____X___X_X__XXX_",
      "_X______X_X_X_X_X_X__X_X_",
      "_X_XX_X_XXX_X_X_X_XX_X___",
      "_X__X_X__X__X_X____X_XXX_",
      "_XX_XXXX_XX_X_XX_X_X_X___",
      "__X_______X____X_X_X_X_XX",
      "_XX_XXXXX_X_X__X_X_X_X___",
      "__X_X_____X_X__X_XXX_XXX_",
      "X_X_XXX_XXX_X_XX_X_X_X___",
      "X_____X_X___X_X______X_XX",
      "XXXXX_X_X_XXX_XX_XXXXX___",
      "____X_X_X_X____X_X____XX_",
      "_XX_X_X_X_XXXX_X______XX_",
      "SX____X_X______X_XXXXXXXT",
    ],
    startPoint: { row: 14, col: 0 },
    targetPoint: { row: 14, col: 24 },
  },
  {
    id: 2,
    title: "Example-2",
    _map: [
      "__________________XXXXXX_",
      "XXXXXX_XX_XXXXXXX_X___XX_",
      "________X_X_______X_X____",
      "_XXXXXXXX_XXXXXXXXX_X_XXX",
      "____________________X____",
      "_XXXXXXXXXXXX_XXXXXXX_X__",
      "_______X____X_X_______XX_",
      "XXX_XX_XX_X_X_X_X_X_XXX__",
      "____X___X_X_X_X_X_X_X___X",
      "_XXXX_XXX_X_XXX_X_X_X_XXX",
      "__X___X___X___X_X_X_X_XX_",
      "XXX_XXX_XXXXX_X_X_X_X__X_",
      "____X___X___X_X_X___XX_X_",
      "XXX_X_X_X_X_X_X_X_X_XX_X_",
      "______X_XTX___X_X_X_XS___",
    ],
    startPoint: { row: 14, col: 21 },
    targetPoint: { row: 14, col: 9 },
  },
  {
    id: 3,
    title: "Example-3",
    _map: [
      "________X___X______X_XXX_",
      "__XX_XX_XXX_X_X__X___X_X_",
      "_XX___X_X_X_X_XX_X_X_XXX_",
      "__X___X___X_X_X__X___X___",
      "_XXX_XX_X_____X_XXXX___X_",
      "___X_X__X_X_X_X__X_X_XXXX",
      "XX_X_X_XX_X_X_XX_XXX_X___",
      "___X_X__X_X_X_X______XXX_",
      "_XXXXXX_X_X_X_X__XXX_X_X_",
      "______XXX_____XX_X_X_XXX_",
      "_XXX_XX_X_X_X_X__X_______",
      "___X_X__X_X_X_X_XX_X_XXXX",
      "XXXX_XX_XXX_XXX__X_X_XS__",
      "___X_X_______X__XX_X_XXX_",
      "TX___XXX_X___X__X__X_____",
    ],
    startPoint: { row: 12, col: 22 },
    targetPoint: { row: 14, col: 0 },
  },
];

export default examples;
